### ISSUE TITLE
StackOverflowError on generating abandoned mineshaft loot

### ISSUE THREAD

**Issue by gardenappl** [railcraft-reborn/railcraft#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The server crashes upon opening an abandoned mineshaft chest. This was tested with the latest version of RailCraft and no other mods.

### Configuration

```Markdown
- Mod version: 1.20.1-1.0.5
- NeoForge/Forge version: 47.1.3
- Minecraft version: 1.20.1
- Are you playing on a server?: no
```

### To Reproduce

1. Run `/loot give <player> loot minecraft:chests/abandoned_mineshaft`
2. server still runs, but no loot is given. (I guess the `/loot` command runs on its own thread?)
3. Run `/setblock ~ ~ ~ chest{LootTable: "minecraft:chests/abandoned_mineshaft"} replace`
4. Open chest
5. Server crashes

### Expected behavior

Loot should be generated properly

### Logs & Environment

```Shell
03:06:29] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.StackOverflowError: null
	at net.minecraft.core.Holder.get(Holder.java:27) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41619_(ItemStack.java:192) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41777_(ItemStack.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_255036_(ItemStack.java:441) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.level.storage.loot.LootTable.m_287134_(LootTable.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:94) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:85) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[client-1.20.1-20230612.114412-srg.jar%23148!/:?] {re:classloading}
	at mods.railcraft.loot.DungeonLootModifier.doApply(DungeonLootModifier.java:37) ~[railcraft-reborn-1.20.1-1.0.5.jar%23147!/:1.20.1-1.0.5] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.1.3-universal.jar%23153!/:?] {re:classloading}

...
```

**Comment by gardenappl** [comment]
Thanks for the fix!
