### ISSUE TITLE
Nightly crashing on empty golden ticket

### ISSUE THREAD

**Issue by greeeen-dev** [railcraft-reborn/railcraft#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When placing a golden ticket with no destination into a locomotive, the game crashes.

### To Reproduce

1. Get a golden ticket
2. Do not set any destination for the ticket
3. Place it into a locomotive

### Expected behavior

The set destination is cleared from the locomotive or the ticket is rejected.

### Logs & Environment

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-06-12 13:13:19
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because the return value of "com.mojang.authlib.GameProfile.getId()" is null
	at net.minecraft.server.players.ServerOpList.m_5981_(ServerOpList.java:36) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.ServerOpList.m_5981_(ServerOpList.java:9) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.StoredUserList.m_11396_(StoredUserList.java:82) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11303_(PlayerList.java:608) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.setDestination(Locomotive.java:338) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.processTicket(Locomotive.java:542) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.m_8119_(Locomotive.java:511) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:671) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.players.ServerOpList.m_5981_(ServerOpList.java:36) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.ServerOpList.m_5981_(ServerOpList.java:9) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.StoredUserList.m_11396_(StoredUserList.java:82) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11303_(PlayerList.java:608) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.setDestination(Locomotive.java:338) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.processTicket(Locomotive.java:542) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at mods.railcraft.world.entity.vehicle.locomotive.Locomotive.m_8119_(Locomotive.java:511) ~[railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar%23146!/:1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:671) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: railcraft:creative_locomotive (mods.railcraft.world.entity.vehicle.locomotive.CreativeLocomotive)
	Entity ID: 1526
	Entity Name: Creative Locomotive
	Entity's Exact location: -2.06, 67.06, 1008.50
	Entity's Block location: World: (-3,67,1008), Section: (at 13,3,0 in -1,4,63; chunk contains blocks -16,-64,1008 to -1,319,1023), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Entity's Momentum: -0.00, -0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Green_mc'/429, l='ServerLevel[New World]', x=-0.11, y=67.00, z=1007.31]]
	Chunk stats: 6178
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4515634 game time, 148870 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 752539272 bytes (717 MiB) / 4026531840 bytes (3840 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2686
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 21099.43
	Virtual memory used (MB): 17885.34
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 169.53
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Green_mc'/429, l='ServerLevel[New World]', x=-0.11, y=67.00, z=1007.31]]
	Data Packs: vanilla, mod:forge, mod:railcraft
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.4
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.4-45.1.0-universal.jar                 |Forge                         |forge                         |45.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		railcraft-1.19.4-13.0.0-beta-5-NIGHTLY-2b8f556.jar|Railcraft                     |railcraft                     |1.19.4-13.0.0-beta-5|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2fd05da0-cc62-487e-a93b-8c6041a17cda
	FML: 45.1
	Forge: net.minecraftforge:45.1.0
```

**Comment by Edivad99** [comment]
The bug has been fixed. The fact remains that if you want to cancel the destination, the train must NOT be set to locked, this is because we have to check if the person inserting the ticket is actually the owner of the train. To clean the destination you have to unlock the train and then insert the clean ticket.
